//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 03:53:17 PM BST 
//


package com.enterprise_architecture.essential.importutility.data.common;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeleteDerivedInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeleteDerivedInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}ClassName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DerivedName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DerivedExtID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sequenceNo" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="matchingMode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeleteDerivedInstanceType", propOrder = {
    "className",
    "derivedName",
    "derivedExtID"
})
public class DeleteDerivedInstanceType {

    @XmlElement(name = "ClassName", required = true)
    protected String className;
    @XmlElement(name = "DerivedName", required = true)
    protected DerivedValue derivedName;
    @XmlElement(name = "DerivedExtID", required = true)
    protected DerivedValue derivedExtID;
    @XmlAttribute
    protected BigInteger sequenceNo;
    @XmlAttribute(required = true)
    protected String matchingMode;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the derivedName property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedValue }
     *     
     */
    public DerivedValue getDerivedName() {
        return derivedName;
    }

    /**
     * Sets the value of the derivedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedValue }
     *     
     */
    public void setDerivedName(DerivedValue value) {
        this.derivedName = value;
    }

    /**
     * Gets the value of the derivedExtID property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedValue }
     *     
     */
    public DerivedValue getDerivedExtID() {
        return derivedExtID;
    }

    /**
     * Sets the value of the derivedExtID property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedValue }
     *     
     */
    public void setDerivedExtID(DerivedValue value) {
        this.derivedExtID = value;
    }

    /**
     * Gets the value of the sequenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNo(BigInteger value) {
        this.sequenceNo = value;
    }

    /**
     * Gets the value of the matchingMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchingMode() {
        return matchingMode;
    }

    /**
     * Sets the value of the matchingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchingMode(String value) {
        this.matchingMode = value;
    }

}
