//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.15 at 12:57:14 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.enterprise-architecture.com/essential/importutility/service/importcallback", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.enterprise_architecture.essential.importutility.service.importcallback;
