//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 02:47:23 PM BST 
//


package com.enterprise_architecture.essential.importutility.data.global;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.enterprise_architecture.essential.importutility.data.common.DerivedValue;


/**
 * <p>Java class for GlobalValueTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalValueTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}GlobalValueTemplateClass"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}GlobalValueTemplateSlot"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}GlobalValueTemplateValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalValueTemplate", propOrder = {
    "globalValueTemplateClass",
    "globalValueTemplateSlot",
    "globalValueTemplateValue"
})
public class GlobalValueTemplate {

    @XmlElement(name = "GlobalValueTemplateClass", required = true)
    protected String globalValueTemplateClass;
    @XmlElement(name = "GlobalValueTemplateSlot", required = true)
    protected String globalValueTemplateSlot;
    @XmlElement(name = "GlobalValueTemplateValue", required = true)
    protected DerivedValue globalValueTemplateValue;

    /**
     * Gets the value of the globalValueTemplateClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalValueTemplateClass() {
        return globalValueTemplateClass;
    }

    /**
     * Sets the value of the globalValueTemplateClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalValueTemplateClass(String value) {
        this.globalValueTemplateClass = value;
    }

    /**
     * Gets the value of the globalValueTemplateSlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalValueTemplateSlot() {
        return globalValueTemplateSlot;
    }

    /**
     * Sets the value of the globalValueTemplateSlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalValueTemplateSlot(String value) {
        this.globalValueTemplateSlot = value;
    }

    /**
     * Gets the value of the globalValueTemplateValue property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedValue }
     *     
     */
    public DerivedValue getGlobalValueTemplateValue() {
        return globalValueTemplateValue;
    }

    /**
     * Sets the value of the globalValueTemplateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedValue }
     *     
     */
    public void setGlobalValueTemplateValue(DerivedValue value) {
        this.globalValueTemplateValue = value;
    }

}
