//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.04 at 04:51:22 PM BST 
//


package org.enterprise_architecture.essential.updatepack;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.enterprise_architecture.essential.updatepack package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.enterprise_architecture.essential.updatepack
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Updatepack }
     * 
     */
    public Updatepack createUpdatepack() {
        return new Updatepack();
    }

    /**
     * Create an instance of {@link Packdefinition }
     * 
     */
    public Packdefinition createPackdefinition() {
        return new Packdefinition();
    }

    /**
     * Create an instance of {@link Packdetails }
     * 
     */
    public Packdetails createPackdetails() {
        return new Packdetails();
    }

}
