//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 02:47:23 PM BST 
//
// Edited 08.03.2017 JWC to add new attributes: xmlTransformFilename, rootXslFilename


package com.enterprise_architecture.essential.importutility.data.global;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ImportActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportActivity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityType"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityStatus"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityDescription"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivitySourceRepository"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityModifiedDate"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityTestedDate"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityToLiveDate"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityRootDirName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}SpreadsheetImportSpecFilename"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}SpreadsheetFilename"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportActivityLogs" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}XMLTransformFilename"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}RootXslFilename"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logImports" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportActivity", propOrder = {
    "importActivityName",
    "importActivityType",
    "importActivityStatus",
    "importActivityDescription",
    "importActivitySourceRepository",
    "importActivityModifiedDate",
    "importActivityTestedDate",
    "importActivityToLiveDate",
    "importActivityRootDirName",
    "spreadsheetImportSpecFilename",
    "spreadsheetFilename",
    "importActivityLogs",
    "xmlTransformFilename",
    "rootXslFilename"
})
public class ImportActivity {

    @XmlElement(name = "ImportActivityName", required = true)
    protected String importActivityName;
    @XmlElement(name = "ImportActivityType", required = true)
    protected String importActivityType;
    @XmlElement(name = "ImportActivityStatus", required = true)
    protected String importActivityStatus;
    @XmlElement(name = "ImportActivityDescription", required = true)
    protected String importActivityDescription;
    @XmlElement(name = "ImportActivitySourceRepository", required = true)
    protected String importActivitySourceRepository;
    @XmlElement(name = "ImportActivityModifiedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar importActivityModifiedDate;
    @XmlElement(name = "ImportActivityTestedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar importActivityTestedDate;
    @XmlElement(name = "ImportActivityToLiveDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar importActivityToLiveDate;
    @XmlElement(name = "ImportActivityRootDirName", required = true)
    protected String importActivityRootDirName;
    @XmlElement(name = "SpreadsheetImportSpecFilename", required = true)
    protected String spreadsheetImportSpecFilename;
    @XmlElement(name = "SpreadsheetFilename", required = true)
    protected String spreadsheetFilename;
    @XmlElement(name = "ImportActivityLogs")
    protected List<ImportActivityLog> importActivityLogs;
    @XmlElement(name = "XmlTransformFilename", required = true)
    protected String xmlTransformFilename; 
    @XmlElement(name = "RootXslFilename", required = true)
    protected String rootXslFilename;    
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected Boolean logImports;

    /**
     * Gets the value of the importActivityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportActivityName() {
        return importActivityName;
    }

    /**
     * Sets the value of the importActivityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportActivityName(String value) {
        this.importActivityName = value;
    }

    /**
     * Gets the value of the importActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportActivityType() {
        return importActivityType;
    }

    /**
     * Sets the value of the importActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportActivityType(String value) {
        this.importActivityType = value;
    }

    /**
     * Gets the value of the importActivityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportActivityStatus() {
        return importActivityStatus;
    }

    /**
     * Sets the value of the importActivityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportActivityStatus(String value) {
        this.importActivityStatus = value;
    }

    /**
     * Gets the value of the importActivityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportActivityDescription() {
        return importActivityDescription;
    }

    /**
     * Sets the value of the importActivityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportActivityDescription(String value) {
        this.importActivityDescription = value;
    }

    /**
     * Gets the value of the importActivitySourceRepository property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportActivitySourceRepository() {
        return importActivitySourceRepository;
    }

    /**
     * Sets the value of the importActivitySourceRepository property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportActivitySourceRepository(String value) {
        this.importActivitySourceRepository = value;
    }

    /**
     * Gets the value of the importActivityModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportActivityModifiedDate() {
        return importActivityModifiedDate;
    }

    /**
     * Sets the value of the importActivityModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportActivityModifiedDate(XMLGregorianCalendar value) {
        this.importActivityModifiedDate = value;
    }

    /**
     * Gets the value of the importActivityTestedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportActivityTestedDate() {
        return importActivityTestedDate;
    }

    /**
     * Sets the value of the importActivityTestedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportActivityTestedDate(XMLGregorianCalendar value) {
        this.importActivityTestedDate = value;
    }

    /**
     * Gets the value of the importActivityToLiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getImportActivityToLiveDate() {
        return importActivityToLiveDate;
    }

    /**
     * Sets the value of the importActivityToLiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setImportActivityToLiveDate(XMLGregorianCalendar value) {
        this.importActivityToLiveDate = value;
    }

    /**
     * Gets the value of the importActivityRootDirName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportActivityRootDirName() {
        return importActivityRootDirName;
    }

    /**
     * Sets the value of the importActivityRootDirName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportActivityRootDirName(String value) {
        this.importActivityRootDirName = value;
    }

    /**
     * Gets the value of the spreadsheetImportSpecFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpreadsheetImportSpecFilename() {
        return spreadsheetImportSpecFilename;
    }

    /**
     * Sets the value of the spreadsheetImportSpecFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpreadsheetImportSpecFilename(String value) {
        this.spreadsheetImportSpecFilename = value;
    }

    /**
     * Gets the value of the spreadsheetFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpreadsheetFilename() {
        return spreadsheetFilename;
    }

    /**
     * Sets the value of the spreadsheetFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpreadsheetFilename(String value) {
        this.spreadsheetFilename = value;
    }

    /**
     * Gets the value of the importActivityLogs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importActivityLogs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportActivityLogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImportActivityLog }
     * 
     * 
     */
    public List<ImportActivityLog> getImportActivityLogs() {
        if (importActivityLogs == null) {
            importActivityLogs = new ArrayList<ImportActivityLog>();
        }
        return this.importActivityLogs;
    }
    
    /**
     * Gets the value of the xmlTransformFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlTransformFilename() {
        return xmlTransformFilename;
    }

    /**
     * Sets the value of the xmlTransformFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlTransformFilename(String value) {
        this.xmlTransformFilename = value;
    }

    /**
     * Gets the value of the rootXslfilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootXslFilename() {
        return rootXslFilename;
    }

    /**
     * Sets the value of the rootXslFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootXslFilename(String value) {
        this.rootXslFilename = value;
    }


    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the logImports property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLogImports() {
        if (logImports == null) {
            return false;
        } else {
            return logImports;
        }
    }

    /**
     * Sets the value of the logImports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLogImports(Boolean value) {
        this.logImports = value;
    }

}
