//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 02:47:23 PM BST 
//
// Updated 08.03.2017 JWC to add xmlTransformFilename, rootXslFilename to ImportActivity
// Updated 06.12.2019 JWC to add importEnvironmentId tag to importEnvironment

package com.enterprise_architecture.essential.importutility.data.global;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import com.enterprise_architecture.essential.importutility.data.common.DerivedInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.DerivedValue;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enterprise_architecture.essential.importutility.data.global package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SpreadsheetFilename_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "SpreadsheetFilename");
    private final static QName _ImportActivities_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivities");
    private final static QName _ImportEnvironments_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironments");
    private final static QName _ImportActivityStatus_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityStatus");
    private final static QName _ImportEnvironmentLocalFolderName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentLocalFolderName");
    private final static QName _ImportEnvironmentLiveSource_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentLiveSource");
    private final static QName _LogUser_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogUser");
    private final static QName _ImportEnvironmentRepositoryPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentRepositoryPath");
    private final static QName _GlobalValueTemplates_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "GlobalValueTemplates");
    private final static QName _ImportEnvironmentRole_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentRole");
    private final static QName _ImportScriptTemplateMode_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportScriptTemplateMode");
    private final static QName _SourceRepositoryName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "SourceRepositoryName");
    private final static QName _GlobalValueTemplateClass_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "GlobalValueTemplateClass");
    private final static QName _ImportActivityLogs_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityLogs");
    private final static QName _ImportEnvironmentName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentName");
    private final static QName _ImportEnvironmentDeploymentType_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentDeploymentType");
    private final static QName _ImportChunkSize_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportChunkSize");
    private final static QName _ExcelImportTemplateImportSpecFilename_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ExcelImportTemplateImportSpecFilename");
    private final static QName _SourceRepositoryDescription_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "SourceRepositoryDescription");
    private final static QName _GlobalInstances_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "GlobalInstances");
    private final static QName _SourceRepositories_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "SourceRepositories");
    private final static QName _LogSourceRepositoryPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogSourceRepositoryPath");
    private final static QName _ExcelImportTemplateDescription_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ExcelImportTemplateDescription");
    private final static QName _LogOutputLogPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogOutputLogPath");
    private final static QName _ExcelImportTemplateExcelFilename_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ExcelImportTemplateExcelFilename");
    private final static QName _ImportActivityTestedDate_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityTestedDate");
    private final static QName _ImportActivityToLiveDate_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityToLiveDate");
    private final static QName _LogUpdatedRepositoryPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogUpdatedRepositoryPath");
    private final static QName _ExcelImportTemplateName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ExcelImportTemplateName");
    private final static QName _ImportActivitySourceRepository_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivitySourceRepository");
    private final static QName _ImportScriptTemplateString_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportScriptTemplateString");
    private final static QName _LogFolderPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogFolderPath");
    private final static QName _ImportUtilityVersion_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportUtilityVersion");
    private final static QName _LogImportScriptPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogImportScriptPath");
    private final static QName _ExcelImportTemplateRootDirName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ExcelImportTemplateRootDirName");
    private final static QName _ImportActivityRootDirName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityRootDirName");
    private final static QName _LogTargetEnvName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogTargetEnvName");
    private final static QName _SpreadsheetImportSpecFilename_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "SpreadsheetImportSpecFilename");
    private final static QName _ImportEnvironmentDescription_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentDescription");
    private final static QName _LogImportSpecPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogImportSpecPath");
    private final static QName _ImportActivityType_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityType");
    private final static QName _ExcelImportTemplates_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ExcelImportTemplates");
    private final static QName _GlobalValueTemplateValue_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "GlobalValueTemplateValue");
    private final static QName _ReferenceEnvironment_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ReferenceEnvironment");
    private final static QName _ImportActivityName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityName");
    private final static QName _ImportActivityModifiedDate_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityModifiedDate");
    private final static QName _ImportScriptTemplates_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportScriptTemplates");
    private final static QName _ImportActivityDescription_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportActivityDescription");
    private final static QName _IncludesDirectoryPath_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "IncludesDirectoryPath");
    private final static QName _ImportEnvironmentViewerURL_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentViewerURL");
    private final static QName _ImportScriptTemplateClassName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportScriptTemplateClassName");
    private final static QName _GlobalValueTemplateSlot_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "GlobalValueTemplateSlot");
    private final static QName _LogTargetEnvType_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "LogTargetEnvType");
    private final static QName _XmlTransformFilename_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "XmlTransformFilename");
    private final static QName _RootXslFilename_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "RootXslFilename");

    /**
     * Added by hand from a generated ObjectFactory.java file - JWC 06.12.2019
     */
    private final static QName _ImportEnvironmentId_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/config", "ImportEnvironmentId");
    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enterprise_architecture.essential.importutility.data.global
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImportActivityLog }
     * 
     */
    public ImportActivityLog createImportActivityLog() {
        return new ImportActivityLog();
    }

    /**
     * Create an instance of {@link ExcelImportTemplate }
     * 
     */
    public ExcelImportTemplate createExcelImportTemplate() {
        return new ExcelImportTemplate();
    }

    /**
     * Create an instance of {@link SourceRepository }
     * 
     */
    public SourceRepository createSourceRepository() {
        return new SourceRepository();
    }

    /**
     * Create an instance of {@link GlobalValueTemplate }
     * 
     */
    public GlobalValueTemplate createGlobalValueTemplate() {
        return new GlobalValueTemplate();
    }

    /**
     * Create an instance of {@link ImportEnvironment }
     * 
     */
    public ImportEnvironment createImportEnvironment() {
        return new ImportEnvironment();
    }

    /**
     * Create an instance of {@link ImportScriptTemplate }
     * 
     */
    public ImportScriptTemplate createImportScriptTemplate() {
        return new ImportScriptTemplate();
    }

    /**
     * Create an instance of {@link ImportActivity }
     * 
     */
    public ImportActivity createImportActivity() {
        return new ImportActivity();
    }

    /**
     * Create an instance of {@link EssentialImportUtility }
     * 
     */
    public EssentialImportUtility createEssentialImportUtility() {
        return new EssentialImportUtility();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "SpreadsheetFilename")
    public JAXBElement<String> createSpreadsheetFilename(String value) {
        return new JAXBElement<String>(_SpreadsheetFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportActivity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivities")
    public JAXBElement<ImportActivity> createImportActivities(ImportActivity value) {
        return new JAXBElement<ImportActivity>(_ImportActivities_QNAME, ImportActivity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportEnvironment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironments")
    public JAXBElement<ImportEnvironment> createImportEnvironments(ImportEnvironment value) {
        return new JAXBElement<ImportEnvironment>(_ImportEnvironments_QNAME, ImportEnvironment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityStatus")
    public JAXBElement<String> createImportActivityStatus(String value) {
        return new JAXBElement<String>(_ImportActivityStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentLocalFolderName")
    public JAXBElement<String> createImportEnvironmentLocalFolderName(String value) {
        return new JAXBElement<String>(_ImportEnvironmentLocalFolderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentLiveSource")
    public JAXBElement<String> createImportEnvironmentLiveSource(String value) {
        return new JAXBElement<String>(_ImportEnvironmentLiveSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogUser")
    public JAXBElement<String> createLogUser(String value) {
        return new JAXBElement<String>(_LogUser_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentRepositoryPath")
    public JAXBElement<String> createImportEnvironmentRepositoryPath(String value) {
        return new JAXBElement<String>(_ImportEnvironmentRepositoryPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GlobalValueTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "GlobalValueTemplates")
    public JAXBElement<GlobalValueTemplate> createGlobalValueTemplates(GlobalValueTemplate value) {
        return new JAXBElement<GlobalValueTemplate>(_GlobalValueTemplates_QNAME, GlobalValueTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentRole")
    public JAXBElement<String> createImportEnvironmentRole(String value) {
        return new JAXBElement<String>(_ImportEnvironmentRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportScriptTemplateMode")
    public JAXBElement<String> createImportScriptTemplateMode(String value) {
        return new JAXBElement<String>(_ImportScriptTemplateMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "SourceRepositoryName")
    public JAXBElement<String> createSourceRepositoryName(String value) {
        return new JAXBElement<String>(_SourceRepositoryName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "GlobalValueTemplateClass")
    public JAXBElement<String> createGlobalValueTemplateClass(String value) {
        return new JAXBElement<String>(_GlobalValueTemplateClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportActivityLog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityLogs")
    public JAXBElement<ImportActivityLog> createImportActivityLogs(ImportActivityLog value) {
        return new JAXBElement<ImportActivityLog>(_ImportActivityLogs_QNAME, ImportActivityLog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentName")
    public JAXBElement<String> createImportEnvironmentName(String value) {
        return new JAXBElement<String>(_ImportEnvironmentName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentDeploymentType")
    public JAXBElement<String> createImportEnvironmentDeploymentType(String value) {
        return new JAXBElement<String>(_ImportEnvironmentDeploymentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportChunkSize")
    public JAXBElement<BigInteger> createImportChunkSize(BigInteger value) {
        return new JAXBElement<BigInteger>(_ImportChunkSize_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ExcelImportTemplateImportSpecFilename")
    public JAXBElement<String> createExcelImportTemplateImportSpecFilename(String value) {
        return new JAXBElement<String>(_ExcelImportTemplateImportSpecFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "SourceRepositoryDescription")
    public JAXBElement<String> createSourceRepositoryDescription(String value) {
        return new JAXBElement<String>(_SourceRepositoryDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "GlobalInstances")
    public JAXBElement<DerivedInstanceType> createGlobalInstances(DerivedInstanceType value) {
        return new JAXBElement<DerivedInstanceType>(_GlobalInstances_QNAME, DerivedInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceRepository }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "SourceRepositories")
    public JAXBElement<SourceRepository> createSourceRepositories(SourceRepository value) {
        return new JAXBElement<SourceRepository>(_SourceRepositories_QNAME, SourceRepository.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogSourceRepositoryPath")
    public JAXBElement<String> createLogSourceRepositoryPath(String value) {
        return new JAXBElement<String>(_LogSourceRepositoryPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ExcelImportTemplateDescription")
    public JAXBElement<String> createExcelImportTemplateDescription(String value) {
        return new JAXBElement<String>(_ExcelImportTemplateDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogOutputLogPath")
    public JAXBElement<String> createLogOutputLogPath(String value) {
        return new JAXBElement<String>(_LogOutputLogPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ExcelImportTemplateExcelFilename")
    public JAXBElement<String> createExcelImportTemplateExcelFilename(String value) {
        return new JAXBElement<String>(_ExcelImportTemplateExcelFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityTestedDate")
    public JAXBElement<XMLGregorianCalendar> createImportActivityTestedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ImportActivityTestedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityToLiveDate")
    public JAXBElement<XMLGregorianCalendar> createImportActivityToLiveDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ImportActivityToLiveDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogUpdatedRepositoryPath")
    public JAXBElement<String> createLogUpdatedRepositoryPath(String value) {
        return new JAXBElement<String>(_LogUpdatedRepositoryPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ExcelImportTemplateName")
    public JAXBElement<String> createExcelImportTemplateName(String value) {
        return new JAXBElement<String>(_ExcelImportTemplateName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivitySourceRepository")
    public JAXBElement<String> createImportActivitySourceRepository(String value) {
        return new JAXBElement<String>(_ImportActivitySourceRepository_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportScriptTemplateString")
    public JAXBElement<String> createImportScriptTemplateString(String value) {
        return new JAXBElement<String>(_ImportScriptTemplateString_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogFolderPath")
    public JAXBElement<String> createLogFolderPath(String value) {
        return new JAXBElement<String>(_LogFolderPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportUtilityVersion")
    public JAXBElement<String> createImportUtilityVersion(String value) {
        return new JAXBElement<String>(_ImportUtilityVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogImportScriptPath")
    public JAXBElement<String> createLogImportScriptPath(String value) {
        return new JAXBElement<String>(_LogImportScriptPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ExcelImportTemplateRootDirName")
    public JAXBElement<String> createExcelImportTemplateRootDirName(String value) {
        return new JAXBElement<String>(_ExcelImportTemplateRootDirName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityRootDirName")
    public JAXBElement<String> createImportActivityRootDirName(String value) {
        return new JAXBElement<String>(_ImportActivityRootDirName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogTargetEnvName")
    public JAXBElement<String> createLogTargetEnvName(String value) {
        return new JAXBElement<String>(_LogTargetEnvName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "SpreadsheetImportSpecFilename")
    public JAXBElement<String> createSpreadsheetImportSpecFilename(String value) {
        return new JAXBElement<String>(_SpreadsheetImportSpecFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentDescription")
    public JAXBElement<String> createImportEnvironmentDescription(String value) {
        return new JAXBElement<String>(_ImportEnvironmentDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogImportSpecPath")
    public JAXBElement<String> createLogImportSpecPath(String value) {
        return new JAXBElement<String>(_LogImportSpecPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityType")
    public JAXBElement<String> createImportActivityType(String value) {
        return new JAXBElement<String>(_ImportActivityType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExcelImportTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ExcelImportTemplates")
    public JAXBElement<ExcelImportTemplate> createExcelImportTemplates(ExcelImportTemplate value) {
        return new JAXBElement<ExcelImportTemplate>(_ExcelImportTemplates_QNAME, ExcelImportTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "GlobalValueTemplateValue")
    public JAXBElement<DerivedValue> createGlobalValueTemplateValue(DerivedValue value) {
        return new JAXBElement<DerivedValue>(_GlobalValueTemplateValue_QNAME, DerivedValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportEnvironment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ReferenceEnvironment")
    public JAXBElement<ImportEnvironment> createReferenceEnvironment(ImportEnvironment value) {
        return new JAXBElement<ImportEnvironment>(_ReferenceEnvironment_QNAME, ImportEnvironment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityName")
    public JAXBElement<String> createImportActivityName(String value) {
        return new JAXBElement<String>(_ImportActivityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityModifiedDate")
    public JAXBElement<XMLGregorianCalendar> createImportActivityModifiedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ImportActivityModifiedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportScriptTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportScriptTemplates")
    public JAXBElement<ImportScriptTemplate> createImportScriptTemplates(ImportScriptTemplate value) {
        return new JAXBElement<ImportScriptTemplate>(_ImportScriptTemplates_QNAME, ImportScriptTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportActivityDescription")
    public JAXBElement<String> createImportActivityDescription(String value) {
        return new JAXBElement<String>(_ImportActivityDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "IncludesDirectoryPath")
    public JAXBElement<String> createIncludesDirectoryPath(String value) {
        return new JAXBElement<String>(_IncludesDirectoryPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentViewerURL")
    public JAXBElement<String> createImportEnvironmentViewerURL(String value) {
        return new JAXBElement<String>(_ImportEnvironmentViewerURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportScriptTemplateClassName")
    public JAXBElement<String> createImportScriptTemplateClassName(String value) {
        return new JAXBElement<String>(_ImportScriptTemplateClassName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "GlobalValueTemplateSlot")
    public JAXBElement<String> createGlobalValueTemplateSlot(String value) {
        return new JAXBElement<String>(_GlobalValueTemplateSlot_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "LogTargetEnvType")
    public JAXBElement<String> createLogTargetEnvType(String value) {
        return new JAXBElement<String>(_LogTargetEnvType_QNAME, String.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "XmlTransformFilename")
    public JAXBElement<String> createXmlTransformFilename(String value) {
        return new JAXBElement<String>(_XmlTransformFilename_QNAME, String.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "RootXslFilename")
    public JAXBElement<String> createRootXslFilename(String value) {
        return new JAXBElement<String>(_RootXslFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * Added by hand from a generated ObjectFactory.java file - JWC 06.12.2019
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/config", name = "ImportEnvironmentId")
    public JAXBElement<String> createImportEnvironmentId(String value) {
        return new JAXBElement<String>(_ImportEnvironmentId_QNAME, String.class, null, value);
    }

}
