//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 02:46:10 PM BST 
//


package com.enterprise_architecture.essential.importutility.data.importspec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.enterprise_architecture.essential.importutility.data.common.DeleteDerivedInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.DeleteSimpleInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.DerivedInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.SimpleInstanceType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.enterprise_architecture.essential.importutility.data.importspec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DerivedInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DerivedInstance");
    private final static QName _WorksheetDescription_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/importspec", "WorksheetDescription");
    private final static QName _DeleteSimpleInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DeleteSimpleInstance");
    private final static QName _DeleteDerivedInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DeleteDerivedInstance");
    private final static QName _SimpleInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "SimpleInstance");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.enterprise_architecture.essential.importutility.data.importspec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpreadsheetImportSpec }
     * 
     */
    public SpreadsheetImportSpec createSpreadsheetImportSpec() {
        return new SpreadsheetImportSpec();
    }

    /**
     * Create an instance of {@link GlobalInstances }
     * 
     */
    public GlobalInstances createGlobalInstances() {
        return new GlobalInstances();
    }

    /**
     * Create an instance of {@link WorksheetImportSpec }
     * 
     */
    public WorksheetImportSpec createWorksheetImportSpec() {
        return new WorksheetImportSpec();
    }

    /**
     * Create an instance of {@link WorksheetInstances }
     * 
     */
    public WorksheetInstances createWorksheetInstances() {
        return new WorksheetInstances();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DerivedInstance")
    public JAXBElement<DerivedInstanceType> createDerivedInstance(DerivedInstanceType value) {
        return new JAXBElement<DerivedInstanceType>(_DerivedInstance_QNAME, DerivedInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/importspec", name = "WorksheetDescription")
    public JAXBElement<String> createWorksheetDescription(String value) {
        return new JAXBElement<String>(_WorksheetDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteSimpleInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DeleteSimpleInstance")
    public JAXBElement<DeleteSimpleInstanceType> createDeleteSimpleInstance(DeleteSimpleInstanceType value) {
        return new JAXBElement<DeleteSimpleInstanceType>(_DeleteSimpleInstance_QNAME, DeleteSimpleInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteDerivedInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DeleteDerivedInstance")
    public JAXBElement<DeleteDerivedInstanceType> createDeleteDerivedInstance(DeleteDerivedInstanceType value) {
        return new JAXBElement<DeleteDerivedInstanceType>(_DeleteDerivedInstance_QNAME, DeleteDerivedInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "SimpleInstance")
    public JAXBElement<SimpleInstanceType> createSimpleInstance(SimpleInstanceType value) {
        return new JAXBElement<SimpleInstanceType>(_SimpleInstance_QNAME, SimpleInstanceType.class, null, value);
    }

}
