//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 02:46:10 PM BST 
//


package com.enterprise_architecture.essential.importutility.data.importspec;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/importspec}GlobalInstances"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/importspec}WorksheetInstances"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/importspec}WorksheetImportSpec" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="import_schema_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalInstances",
    "worksheetInstances",
    "worksheetImportSpec"
})
@XmlRootElement(name = "SpreadsheetImportSpec")
public class SpreadsheetImportSpec {

    @XmlElement(name = "GlobalInstances", required = true)
    protected GlobalInstances globalInstances;
    @XmlElement(name = "WorksheetInstances", required = true)
    protected WorksheetInstances worksheetInstances;
    @XmlElement(name = "WorksheetImportSpec")
    protected List<WorksheetImportSpec> worksheetImportSpec;
    @XmlAttribute(name = "import_schema_version", required = true)
    protected String importSchemaVersion;

    /**
     * Gets the value of the globalInstances property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalInstances }
     *     
     */
    public GlobalInstances getGlobalInstances() {
        return globalInstances;
    }

    /**
     * Sets the value of the globalInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalInstances }
     *     
     */
    public void setGlobalInstances(GlobalInstances value) {
        this.globalInstances = value;
    }

    /**
     * Gets the value of the worksheetInstances property.
     * 
     * @return
     *     possible object is
     *     {@link WorksheetInstances }
     *     
     */
    public WorksheetInstances getWorksheetInstances() {
        return worksheetInstances;
    }

    /**
     * Sets the value of the worksheetInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorksheetInstances }
     *     
     */
    public void setWorksheetInstances(WorksheetInstances value) {
        this.worksheetInstances = value;
    }

    /**
     * Gets the value of the worksheetImportSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the worksheetImportSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorksheetImportSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorksheetImportSpec }
     * 
     * 
     */
    public List<WorksheetImportSpec> getWorksheetImportSpec() {
        if (worksheetImportSpec == null) {
            worksheetImportSpec = new ArrayList<WorksheetImportSpec>();
        }
        return this.worksheetImportSpec;
    }

    /**
     * Gets the value of the importSchemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportSchemaVersion() {
        return importSchemaVersion;
    }

    /**
     * Sets the value of the importSchemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportSchemaVersion(String value) {
        this.importSchemaVersion = value;
    }

}
