//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.08 at 02:46:10 PM BST 
//


package com.enterprise_architecture.essential.importutility.data.importspec;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.enterprise_architecture.essential.importutility.data.common.DeleteDerivedInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.DeleteSimpleInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.DerivedInstanceType;
import com.enterprise_architecture.essential.importutility.data.common.SimpleInstanceType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DerivedInstance"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}SimpleInstance"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DeleteDerivedInstance"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DeleteSimpleInstance"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/importspec}WorksheetDescription"/>
 *       &lt;/sequence>
 *       &lt;attribute name="firstRow" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="lastRow" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="sequenceNo" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="sheetNo" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="imported" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance",
    "worksheetDescription"
})
@XmlRootElement(name = "WorksheetImportSpec")
public class WorksheetImportSpec {

    @XmlElements({
        @XmlElement(name = "DeleteSimpleInstance", namespace = "http://www.enterprise-architecture.org/essential/importutility/common", type = DeleteSimpleInstanceType.class),
        @XmlElement(name = "DeleteDerivedInstance", namespace = "http://www.enterprise-architecture.org/essential/importutility/common", type = DeleteDerivedInstanceType.class),
        @XmlElement(name = "SimpleInstance", namespace = "http://www.enterprise-architecture.org/essential/importutility/common", type = SimpleInstanceType.class),
        @XmlElement(name = "DerivedInstance", namespace = "http://www.enterprise-architecture.org/essential/importutility/common", type = DerivedInstanceType.class)
    })
    protected List<Object> derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance;
    @XmlElement(name = "WorksheetDescription", required = true)
    protected String worksheetDescription;
    @XmlAttribute(required = true)
    protected BigInteger firstRow;
    @XmlAttribute(required = true)
    protected BigInteger lastRow;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(required = true)
    protected BigInteger sequenceNo;
    @XmlAttribute(required = true)
    protected BigInteger sheetNo;
    @XmlAttribute(required = true)
    protected boolean imported;

    /**
     * Gets the value of the derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDerivedInstanceOrSimpleInstanceOrDeleteDerivedInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeleteSimpleInstanceType }
     * {@link DeleteDerivedInstanceType }
     * {@link SimpleInstanceType }
     * {@link DerivedInstanceType }
     * 
     * 
     */
    public List<Object> getDerivedInstanceOrSimpleInstanceOrDeleteDerivedInstance() {
        if (derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance == null) {
            derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance = new ArrayList<Object>();
        }
        return this.derivedInstanceOrSimpleInstanceOrDeleteDerivedInstance;
    }

    /**
     * Gets the value of the worksheetDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorksheetDescription() {
        return worksheetDescription;
    }

    /**
     * Sets the value of the worksheetDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorksheetDescription(String value) {
        this.worksheetDescription = value;
    }

    /**
     * Gets the value of the firstRow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFirstRow() {
        return firstRow;
    }

    /**
     * Sets the value of the firstRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFirstRow(BigInteger value) {
        this.firstRow = value;
    }

    /**
     * Gets the value of the lastRow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastRow() {
        return lastRow;
    }

    /**
     * Sets the value of the lastRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastRow(BigInteger value) {
        this.lastRow = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sequenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNo(BigInteger value) {
        this.sequenceNo = value;
    }

    /**
     * Gets the value of the sheetNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSheetNo() {
        return sheetNo;
    }

    /**
     * Sets the value of the sheetNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSheetNo(BigInteger value) {
        this.sheetNo = value;
    }

    /**
     * Gets the value of the imported property.
     * 
     */
    public boolean isImported() {
        return imported;
    }

    /**
     * Sets the value of the imported property.
     * 
     */
    public void setImported(boolean value) {
        this.imported = value;
    }

}
