//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 06:02:25 PM GMT 
//


package org.enterprise_architecture.essential.importutility.common;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DerivedInstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DerivedInstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}VariableName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}ClassName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DerivedName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DerivedExtID"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}InstanceSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}RemoveInstanceSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DeleteInstanceSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}RemoveAllInstanceSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DeleteAllInstanceSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}SimpleSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}DerivedSimpleSlot"/>
 *           &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}PrimitiveSlot"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="sequenceNo" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="matchingMode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DerivedInstanceType", propOrder = {
    "variableName",
    "className",
    "derivedName",
    "derivedExtID",
    "instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot"
})
public class DerivedInstanceType {

    @XmlElement(name = "VariableName", required = true)
    protected String variableName;
    @XmlElement(name = "ClassName", required = true)
    protected String className;
    @XmlElement(name = "DerivedName", required = true)
    protected DerivedValue derivedName;
    @XmlElement(name = "DerivedExtID", required = true)
    protected DerivedValue derivedExtID;
    @XmlElements({
        @XmlElement(name = "InstanceSlot", type = InstanceSlot.class),
        @XmlElement(name = "RemoveInstanceSlot", type = RemoveInstanceSlot.class),
        @XmlElement(name = "DeleteInstanceSlot", type = DeleteInstanceSlot.class),
        @XmlElement(name = "RemoveAllInstanceSlot", type = RemoveAllInstanceSlot.class),
        @XmlElement(name = "DeleteAllInstanceSlot", type = DeleteAllInstanceSlot.class),
        @XmlElement(name = "SimpleSlot", type = SimpleSlot.class),
        @XmlElement(name = "DerivedSimpleSlot", type = DerivedSimpleSlot.class),
        @XmlElement(name = "PrimitiveSlot", type = PrimitiveSlot.class)
    })
    protected List<Object> instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot;
    @XmlAttribute(name = "sequenceNo")
    protected BigInteger sequenceNo;
    @XmlAttribute(name = "matchingMode", required = true)
    protected String matchingMode;

    /**
     * Gets the value of the variableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableName() {
        return variableName;
    }

    /**
     * Sets the value of the variableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableName(String value) {
        this.variableName = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the derivedName property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedValue }
     *     
     */
    public DerivedValue getDerivedName() {
        return derivedName;
    }

    /**
     * Sets the value of the derivedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedValue }
     *     
     */
    public void setDerivedName(DerivedValue value) {
        this.derivedName = value;
    }

    /**
     * Gets the value of the derivedExtID property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedValue }
     *     
     */
    public DerivedValue getDerivedExtID() {
        return derivedExtID;
    }

    /**
     * Sets the value of the derivedExtID property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedValue }
     *     
     */
    public void setDerivedExtID(DerivedValue value) {
        this.derivedExtID = value;
    }

    /**
     * Gets the value of the instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstanceSlot }
     * {@link RemoveInstanceSlot }
     * {@link DeleteInstanceSlot }
     * {@link RemoveAllInstanceSlot }
     * {@link DeleteAllInstanceSlot }
     * {@link SimpleSlot }
     * {@link DerivedSimpleSlot }
     * {@link PrimitiveSlot }
     * 
     * 
     */
    public List<Object> getInstanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot() {
        if (instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot == null) {
            instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot = new ArrayList<Object>();
        }
        return this.instanceSlotOrRemoveInstanceSlotOrDeleteInstanceSlot;
    }

    /**
     * Gets the value of the sequenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNo(BigInteger value) {
        this.sequenceNo = value;
    }

    /**
     * Gets the value of the matchingMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchingMode() {
        return matchingMode;
    }

    /**
     * Sets the value of the matchingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchingMode(String value) {
        this.matchingMode = value;
    }

}
