//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 06:02:25 PM GMT 
//


package org.enterprise_architecture.essential.importutility.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.enterprise_architecture.essential.importutility.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DerivedSlotValue_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DerivedSlotValue");
    private final static QName _DeleteDerivedInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DeleteDerivedInstance");
    private final static QName _VariableName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "VariableName");
    private final static QName _PrimitiveSlotType_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "PrimitiveSlotType");
    private final static QName _SimpleInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "SimpleInstance");
    private final static QName _ConditionalRef_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "ConditionalRef");
    private final static QName _ClassName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "ClassName");
    private final static QName _SlotName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "SlotName");
    private final static QName _InstanceSlotVar_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "InstanceSlotVar");
    private final static QName _DeleteSimpleInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DeleteSimpleInstance");
    private final static QName _ExtIDRef_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "ExtIDRef");
    private final static QName _DerivedInstance_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DerivedInstance");
    private final static QName _NameRef_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "NameRef");
    private final static QName _DerivedName_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DerivedName");
    private final static QName _DerivedExtID_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "DerivedExtID");
    private final static QName _SlotValueRef_QNAME = new QName("http://www.enterprise-architecture.org/essential/importutility/common", "SlotValueRef");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.enterprise_architecture.essential.importutility.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DerivedInstanceType }
     * 
     */
    public DerivedInstanceType createDerivedInstanceType() {
        return new DerivedInstanceType();
    }

    /**
     * Create an instance of {@link DerivedValue }
     * 
     */
    public DerivedValue createDerivedValue() {
        return new DerivedValue();
    }

    /**
     * Create an instance of {@link InstanceSlot }
     * 
     */
    public InstanceSlot createInstanceSlot() {
        return new InstanceSlot();
    }

    /**
     * Create an instance of {@link SimpleInstanceType }
     * 
     */
    public SimpleInstanceType createSimpleInstanceType() {
        return new SimpleInstanceType();
    }

    /**
     * Create an instance of {@link RemoveInstanceSlot }
     * 
     */
    public RemoveInstanceSlot createRemoveInstanceSlot() {
        return new RemoveInstanceSlot();
    }

    /**
     * Create an instance of {@link DerivedSimpleSlot }
     * 
     */
    public DerivedSimpleSlot createDerivedSimpleSlot() {
        return new DerivedSimpleSlot();
    }

    /**
     * Create an instance of {@link SimpleSlot }
     * 
     */
    public SimpleSlot createSimpleSlot() {
        return new SimpleSlot();
    }

    /**
     * Create an instance of {@link DerivedValueRef }
     * 
     */
    public DerivedValueRef createDerivedValueRef() {
        return new DerivedValueRef();
    }

    /**
     * Create an instance of {@link PrimitiveSlot }
     * 
     */
    public PrimitiveSlot createPrimitiveSlot() {
        return new PrimitiveSlot();
    }

    /**
     * Create an instance of {@link DeleteSimpleInstanceType }
     * 
     */
    public DeleteSimpleInstanceType createDeleteSimpleInstanceType() {
        return new DeleteSimpleInstanceType();
    }

    /**
     * Create an instance of {@link DerivedValueString }
     * 
     */
    public DerivedValueString createDerivedValueString() {
        return new DerivedValueString();
    }

    /**
     * Create an instance of {@link RemoveAllInstanceSlot }
     * 
     */
    public RemoveAllInstanceSlot createRemoveAllInstanceSlot() {
        return new RemoveAllInstanceSlot();
    }

    /**
     * Create an instance of {@link DeleteDerivedInstanceType }
     * 
     */
    public DeleteDerivedInstanceType createDeleteDerivedInstanceType() {
        return new DeleteDerivedInstanceType();
    }

    /**
     * Create an instance of {@link DeleteAllInstanceSlot }
     * 
     */
    public DeleteAllInstanceSlot createDeleteAllInstanceSlot() {
        return new DeleteAllInstanceSlot();
    }

    /**
     * Create an instance of {@link DeleteInstanceSlot }
     * 
     */
    public DeleteInstanceSlot createDeleteInstanceSlot() {
        return new DeleteInstanceSlot();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DerivedSlotValue")
    public JAXBElement<DerivedValue> createDerivedSlotValue(DerivedValue value) {
        return new JAXBElement<DerivedValue>(_DerivedSlotValue_QNAME, DerivedValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteDerivedInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DeleteDerivedInstance")
    public JAXBElement<DeleteDerivedInstanceType> createDeleteDerivedInstance(DeleteDerivedInstanceType value) {
        return new JAXBElement<DeleteDerivedInstanceType>(_DeleteDerivedInstance_QNAME, DeleteDerivedInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "VariableName")
    public JAXBElement<String> createVariableName(String value) {
        return new JAXBElement<String>(_VariableName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "PrimitiveSlotType")
    public JAXBElement<String> createPrimitiveSlotType(String value) {
        return new JAXBElement<String>(_PrimitiveSlotType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "SimpleInstance")
    public JAXBElement<SimpleInstanceType> createSimpleInstance(SimpleInstanceType value) {
        return new JAXBElement<SimpleInstanceType>(_SimpleInstance_QNAME, SimpleInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "ConditionalRef")
    public JAXBElement<String> createConditionalRef(String value) {
        return new JAXBElement<String>(_ConditionalRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "ClassName")
    public JAXBElement<String> createClassName(String value) {
        return new JAXBElement<String>(_ClassName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "SlotName")
    public JAXBElement<String> createSlotName(String value) {
        return new JAXBElement<String>(_SlotName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "InstanceSlotVar")
    public JAXBElement<String> createInstanceSlotVar(String value) {
        return new JAXBElement<String>(_InstanceSlotVar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteSimpleInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DeleteSimpleInstance")
    public JAXBElement<DeleteSimpleInstanceType> createDeleteSimpleInstance(DeleteSimpleInstanceType value) {
        return new JAXBElement<DeleteSimpleInstanceType>(_DeleteSimpleInstance_QNAME, DeleteSimpleInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "ExtIDRef")
    public JAXBElement<String> createExtIDRef(String value) {
        return new JAXBElement<String>(_ExtIDRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DerivedInstance")
    public JAXBElement<DerivedInstanceType> createDerivedInstance(DerivedInstanceType value) {
        return new JAXBElement<DerivedInstanceType>(_DerivedInstance_QNAME, DerivedInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "NameRef")
    public JAXBElement<String> createNameRef(String value) {
        return new JAXBElement<String>(_NameRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DerivedName")
    public JAXBElement<DerivedValue> createDerivedName(DerivedValue value) {
        return new JAXBElement<DerivedValue>(_DerivedName_QNAME, DerivedValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DerivedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "DerivedExtID")
    public JAXBElement<DerivedValue> createDerivedExtID(DerivedValue value) {
        return new JAXBElement<DerivedValue>(_DerivedExtID_QNAME, DerivedValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.enterprise-architecture.org/essential/importutility/common", name = "SlotValueRef")
    public JAXBElement<String> createSlotValueRef(String value) {
        return new JAXBElement<String>(_SlotValueRef_QNAME, String.class, null, value);
    }

}
