//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 06:02:25 PM GMT 
//


package org.enterprise_architecture.essential.importutility.common;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}SlotName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/common}SlotValueRef"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sequenceNo" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "slotName",
    "slotValueRef"
})
@XmlRootElement(name = "SimpleSlot")
public class SimpleSlot {

    @XmlElement(name = "SlotName", required = true)
    protected String slotName;
    @XmlElement(name = "SlotValueRef", required = true)
    protected String slotValueRef;
    @XmlAttribute(name = "sequenceNo")
    protected BigInteger sequenceNo;

    /**
     * Gets the value of the slotName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlotName() {
        return slotName;
    }

    /**
     * Sets the value of the slotName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlotName(String value) {
        this.slotName = value;
    }

    /**
     * Gets the value of the slotValueRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlotValueRef() {
        return slotValueRef;
    }

    /**
     * Sets the value of the slotValueRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlotValueRef(String value) {
        this.slotValueRef = value;
    }

    /**
     * Gets the value of the sequenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNo(BigInteger value) {
        this.sequenceNo = value;
    }

}
