//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 06:02:25 PM GMT 
//


package org.enterprise_architecture.essential.importutility.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExcelImportTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExcelImportTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ExcelImportTemplateName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ExcelImportTemplateDescription"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ExcelImportTemplateRootDirName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ExcelImportTemplateExcelFilename"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ExcelImportTemplateImportSpecFilename"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExcelImportTemplate", propOrder = {
    "excelImportTemplateName",
    "excelImportTemplateDescription",
    "excelImportTemplateRootDirName",
    "excelImportTemplateExcelFilename",
    "excelImportTemplateImportSpecFilename"
})
public class ExcelImportTemplate {

    @XmlElement(name = "ExcelImportTemplateName", required = true)
    protected String excelImportTemplateName;
    @XmlElement(name = "ExcelImportTemplateDescription", required = true)
    protected String excelImportTemplateDescription;
    @XmlElement(name = "ExcelImportTemplateRootDirName", required = true)
    protected String excelImportTemplateRootDirName;
    @XmlElement(name = "ExcelImportTemplateExcelFilename", required = true)
    protected String excelImportTemplateExcelFilename;
    @XmlElement(name = "ExcelImportTemplateImportSpecFilename", required = true)
    protected String excelImportTemplateImportSpecFilename;

    /**
     * Gets the value of the excelImportTemplateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcelImportTemplateName() {
        return excelImportTemplateName;
    }

    /**
     * Sets the value of the excelImportTemplateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcelImportTemplateName(String value) {
        this.excelImportTemplateName = value;
    }

    /**
     * Gets the value of the excelImportTemplateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcelImportTemplateDescription() {
        return excelImportTemplateDescription;
    }

    /**
     * Sets the value of the excelImportTemplateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcelImportTemplateDescription(String value) {
        this.excelImportTemplateDescription = value;
    }

    /**
     * Gets the value of the excelImportTemplateRootDirName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcelImportTemplateRootDirName() {
        return excelImportTemplateRootDirName;
    }

    /**
     * Sets the value of the excelImportTemplateRootDirName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcelImportTemplateRootDirName(String value) {
        this.excelImportTemplateRootDirName = value;
    }

    /**
     * Gets the value of the excelImportTemplateExcelFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcelImportTemplateExcelFilename() {
        return excelImportTemplateExcelFilename;
    }

    /**
     * Sets the value of the excelImportTemplateExcelFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcelImportTemplateExcelFilename(String value) {
        this.excelImportTemplateExcelFilename = value;
    }

    /**
     * Gets the value of the excelImportTemplateImportSpecFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcelImportTemplateImportSpecFilename() {
        return excelImportTemplateImportSpecFilename;
    }

    /**
     * Sets the value of the excelImportTemplateImportSpecFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcelImportTemplateImportSpecFilename(String value) {
        this.excelImportTemplateImportSpecFilename = value;
    }

}
