//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 06:02:25 PM GMT 
//


package org.enterprise_architecture.essential.importutility.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ImportEnvironment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportEnvironment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentId" minOccurs="0"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentDescription"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentRole"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentDeploymentType"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentLiveSource"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentRepositoryPath"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentLocalFolderName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportEnvironmentViewerURL"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="viewer_username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="viewer_password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="backupBefore" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="usedAsReference" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="lastUpdated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="hostname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="projectName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportEnvironment", propOrder = {
    "importEnvironmentId",
    "importEnvironmentName",
    "importEnvironmentDescription",
    "importEnvironmentRole",
    "importEnvironmentDeploymentType",
    "importEnvironmentLiveSource",
    "importEnvironmentRepositoryPath",
    "importEnvironmentLocalFolderName",
    "importEnvironmentViewerURL"
})
public class ImportEnvironment {

    @XmlElement(name = "ImportEnvironmentId")
    protected String importEnvironmentId;
    @XmlElement(name = "ImportEnvironmentName", required = true)
    protected String importEnvironmentName;
    @XmlElement(name = "ImportEnvironmentDescription", required = true)
    protected String importEnvironmentDescription;
    @XmlElement(name = "ImportEnvironmentRole", required = true)
    protected String importEnvironmentRole;
    @XmlElement(name = "ImportEnvironmentDeploymentType", required = true)
    protected String importEnvironmentDeploymentType;
    @XmlElement(name = "ImportEnvironmentLiveSource", required = true)
    protected String importEnvironmentLiveSource;
    @XmlElement(name = "ImportEnvironmentRepositoryPath", required = true)
    protected String importEnvironmentRepositoryPath;
    @XmlElement(name = "ImportEnvironmentLocalFolderName", required = true)
    protected String importEnvironmentLocalFolderName;
    @XmlElement(name = "ImportEnvironmentViewerURL", required = true)
    protected String importEnvironmentViewerURL;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "viewer_username")
    protected String viewerUsername;
    @XmlAttribute(name = "viewer_password")
    protected String viewerPassword;
    @XmlAttribute(name = "backupBefore")
    protected Boolean backupBefore;
    @XmlAttribute(name = "usedAsReference")
    protected Boolean usedAsReference;
    @XmlAttribute(name = "lastUpdated")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdated;
    @XmlAttribute(name = "hostname")
    protected String hostname;
    @XmlAttribute(name = "username")
    protected String username;
    @XmlAttribute(name = "password")
    protected String password;
    @XmlAttribute(name = "projectName")
    protected String projectName;

    /**
     * Gets the value of the importEnvironmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentId() {
        return importEnvironmentId;
    }

    /**
     * Sets the value of the importEnvironmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentId(String value) {
        this.importEnvironmentId = value;
    }

    /**
     * Gets the value of the importEnvironmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentName() {
        return importEnvironmentName;
    }

    /**
     * Sets the value of the importEnvironmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentName(String value) {
        this.importEnvironmentName = value;
    }

    /**
     * Gets the value of the importEnvironmentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentDescription() {
        return importEnvironmentDescription;
    }

    /**
     * Sets the value of the importEnvironmentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentDescription(String value) {
        this.importEnvironmentDescription = value;
    }

    /**
     * Gets the value of the importEnvironmentRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentRole() {
        return importEnvironmentRole;
    }

    /**
     * Sets the value of the importEnvironmentRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentRole(String value) {
        this.importEnvironmentRole = value;
    }

    /**
     * Gets the value of the importEnvironmentDeploymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentDeploymentType() {
        return importEnvironmentDeploymentType;
    }

    /**
     * Sets the value of the importEnvironmentDeploymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentDeploymentType(String value) {
        this.importEnvironmentDeploymentType = value;
    }

    /**
     * Gets the value of the importEnvironmentLiveSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentLiveSource() {
        return importEnvironmentLiveSource;
    }

    /**
     * Sets the value of the importEnvironmentLiveSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentLiveSource(String value) {
        this.importEnvironmentLiveSource = value;
    }

    /**
     * Gets the value of the importEnvironmentRepositoryPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentRepositoryPath() {
        return importEnvironmentRepositoryPath;
    }

    /**
     * Sets the value of the importEnvironmentRepositoryPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentRepositoryPath(String value) {
        this.importEnvironmentRepositoryPath = value;
    }

    /**
     * Gets the value of the importEnvironmentLocalFolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentLocalFolderName() {
        return importEnvironmentLocalFolderName;
    }

    /**
     * Sets the value of the importEnvironmentLocalFolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentLocalFolderName(String value) {
        this.importEnvironmentLocalFolderName = value;
    }

    /**
     * Gets the value of the importEnvironmentViewerURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportEnvironmentViewerURL() {
        return importEnvironmentViewerURL;
    }

    /**
     * Sets the value of the importEnvironmentViewerURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportEnvironmentViewerURL(String value) {
        this.importEnvironmentViewerURL = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the viewerUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewerUsername() {
        return viewerUsername;
    }

    /**
     * Sets the value of the viewerUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewerUsername(String value) {
        this.viewerUsername = value;
    }

    /**
     * Gets the value of the viewerPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewerPassword() {
        return viewerPassword;
    }

    /**
     * Sets the value of the viewerPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewerPassword(String value) {
        this.viewerPassword = value;
    }

    /**
     * Gets the value of the backupBefore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBackupBefore() {
        return backupBefore;
    }

    /**
     * Sets the value of the backupBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackupBefore(Boolean value) {
        this.backupBefore = value;
    }

    /**
     * Gets the value of the usedAsReference property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsedAsReference() {
        return usedAsReference;
    }

    /**
     * Sets the value of the usedAsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsedAsReference(Boolean value) {
        this.usedAsReference = value;
    }

    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdated(XMLGregorianCalendar value) {
        this.lastUpdated = value;
    }

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

}
