//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.06 at 06:02:25 PM GMT 
//


package org.enterprise_architecture.essential.importutility.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImportScriptTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportScriptTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportScriptTemplateClassName"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportScriptTemplateMode"/>
 *         &lt;element ref="{http://www.enterprise-architecture.org/essential/importutility/config}ImportScriptTemplateString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportScriptTemplate", propOrder = {
    "importScriptTemplateClassName",
    "importScriptTemplateMode",
    "importScriptTemplateString"
})
public class ImportScriptTemplate {

    @XmlElement(name = "ImportScriptTemplateClassName", required = true)
    protected String importScriptTemplateClassName;
    @XmlElement(name = "ImportScriptTemplateMode", required = true)
    protected String importScriptTemplateMode;
    @XmlElement(name = "ImportScriptTemplateString", required = true)
    protected String importScriptTemplateString;

    /**
     * Gets the value of the importScriptTemplateClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportScriptTemplateClassName() {
        return importScriptTemplateClassName;
    }

    /**
     * Sets the value of the importScriptTemplateClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportScriptTemplateClassName(String value) {
        this.importScriptTemplateClassName = value;
    }

    /**
     * Gets the value of the importScriptTemplateMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportScriptTemplateMode() {
        return importScriptTemplateMode;
    }

    /**
     * Sets the value of the importScriptTemplateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportScriptTemplateMode(String value) {
        this.importScriptTemplateMode = value;
    }

    /**
     * Gets the value of the importScriptTemplateString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportScriptTemplateString() {
        return importScriptTemplateString;
    }

    /**
     * Sets the value of the importScriptTemplateString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportScriptTemplateString(String value) {
        this.importScriptTemplateString = value;
    }

}
