//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.04 at 04:51:22 PM BST 
//


package org.enterprise_architecture.essential.updatepack;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updatename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updatedescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pack" type="{http://www.enterprise-architecture.org/essential/updatepack}packdefinition" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "updatename",
    "updatedescription",
    "pack"
})
@XmlRootElement(name = "updatepack")
public class Updatepack {

    @XmlElement(required = true)
    protected String updatename;
    @XmlElement(required = true)
    protected String updatedescription;
    @XmlElement(required = true)
    protected List<Packdefinition> pack;

    /**
     * Gets the value of the updatename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatename() {
        return updatename;
    }

    /**
     * Sets the value of the updatename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatename(String value) {
        this.updatename = value;
    }

    /**
     * Gets the value of the updatedescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedescription() {
        return updatedescription;
    }

    /**
     * Sets the value of the updatedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedescription(String value) {
        this.updatedescription = value;
    }

    /**
     * Gets the value of the pack property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pack property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Packdefinition }
     * 
     * 
     */
    public List<Packdefinition> getPack() {
        if (pack == null) {
            pack = new ArrayList<Packdefinition>();
        }
        return this.pack;
    }

}
